DROP TABLE IF EXISTS order_foods;

DROP TABLE IF EXISTS foods;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS tables;

DROP TABLE IF EXISTS restaurant_photos;

DROP TABLE IF EXISTS restaurants;

DROP TABLE IF EXISTS user_tokens;

DROP TABLE IF EXISTS users;

